branch-defaults:
  default:
    environment: Udagramapi-env
  deploy:
    artifact: www/Archive.zip
environment-defaults:
  Udagramapi-env:
    branch: null
    repository: null
global:
  application_name: udagramApi
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
