branch-defaults:
  default:
    environment: Udagramapi-env
  deploy:
    artifact: www/Archive.zip
global:
  application_name: udagramApi
  branch: null
  default_ec2_keyname: vockey
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
